# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog
email: wallefsousa1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  O Jekyll é um gerador de site estático, simples, com reconhecimento de blogs, 
  para sites pessoais, de projetos ou de organizações. Escrito em Ruby
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: ""
twitter_username: twitter_Blog
github_username:  github_WallefS
facebook_username: wallefsousa

# Build settings
markdown: kramdown
#permalink: /:categories/:year/:month/:day/:title
#permalink: /:year/:month/:day/:title
permalink: /:title



theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
